/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.gatorsoft.aerodeskpro.gui;
    
import com.gatorsoft.aerodeskpro.gui.DashboardP;
import com.formdev.flatlaf.FlatIntelliJLaf;
import java.awt.BorderLayout;
import javax.swing.SwingUtilities;

/**
 *
 * @author Oshan
 */
public class MainMenue extends javax.swing.JFrame {

    /**
     * Creates new form FlightManagement
     */
    public MainMenue() {
        initComponents();
        this.setExtendedState(MainMenue.MAXIMIZED_BOTH);
        DashboardP();
    }
    
    private void DashboardP (){
        display.removeAll();
        DashboardP dashboard = new DashboardP();
        display.setLayout(new BorderLayout());
        display.add(dashboard, BorderLayout.CENTER);

        // Revalidate and repaint the panel to ensure it's updated correctly
        display.revalidate();
        display.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        dashBoardBtn = new javax.swing.JButton();
        aircraft = new javax.swing.JButton();
        act = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        baggage = new javax.swing.JButton();
        baggageT = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        PassangerM = new javax.swing.JButton();
        roles = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        terminal = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        setti = new javax.swing.JButton();
        display = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(new java.awt.GridLayout(20, 1, 10, 0));

        dashBoardBtn.setText(" Dashboard");
        dashBoardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashBoardBtnActionPerformed(evt);
            }
        });
        jPanel5.add(dashBoardBtn);

        aircraft.setText("Aircraft");
        aircraft.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aircraftActionPerformed(evt);
            }
        });
        jPanel5.add(aircraft);

        act.setText("Aircraft Types");
        act.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actActionPerformed(evt);
            }
        });
        jPanel5.add(act);

        jButton4.setText("Airlines");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4);

        baggage.setText("Baggage");
        baggage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baggageActionPerformed(evt);
            }
        });
        jPanel5.add(baggage);

        baggageT.setText("Baggage Tracking");
        baggageT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                baggageTActionPerformed(evt);
            }
        });
        jPanel5.add(baggageT);

        jButton7.setText("Bookings");
        jPanel5.add(jButton7);

        jButton8.setText("Email Tokens");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton8);

        jButton9.setText("Flights");
        jPanel5.add(jButton9);

        jButton10.setText("Flight Status History");
        jPanel5.add(jButton10);

        jButton11.setText("Gates");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11);

        jButton12.setText("Gate Assignments");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12);

        PassangerM.setText("Passangers");
        PassangerM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassangerMActionPerformed(evt);
            }
        });
        jPanel5.add(PassangerM);

        roles.setText("Roles");
        roles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rolesActionPerformed(evt);
            }
        });
        jPanel5.add(roles);

        jButton15.setText("Staff");
        jPanel5.add(jButton15);

        jButton16.setText("System logs");
        jPanel5.add(jButton16);

        terminal.setText("Terminals");
        terminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terminalActionPerformed(evt);
            }
        });
        jPanel5.add(terminal);

        jButton18.setText("User Roles");
        jPanel5.add(jButton18);

        jButton19.setText("User Sessions");
        jPanel5.add(jButton19);

        setti.setText("Settings");
        setti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settiActionPerformed(evt);
            }
        });
        jPanel5.add(setti);

        javax.swing.GroupLayout displayLayout = new javax.swing.GroupLayout(display);
        display.setLayout(displayLayout);
        displayLayout.setHorizontalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 554, Short.MAX_VALUE)
        );
        displayLayout.setVerticalGroup(
            displayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(display, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aircraftActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aircraftActionPerformed
        display.removeAll();
        AirCraftManagement1 acm = new AirCraftManagement1();
        display.add(acm, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_aircraftActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton12ActionPerformed

    private void dashBoardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashBoardBtnActionPerformed
        display.removeAll();
        DashboardP dash = new DashboardP();
        display.add(dash, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_dashBoardBtnActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void actActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actActionPerformed
        display.removeAll();
        AircraftTypes act = new AircraftTypes();
        display.add(act, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_actActionPerformed

    private void baggageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baggageActionPerformed
        display.removeAll();
        BaggageManagement baggage = new BaggageManagement();
        display.add(baggage, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_baggageActionPerformed

    private void baggageTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_baggageTActionPerformed
        display.removeAll();
        BaggageTracking baggaget = new BaggageTracking();
        display.add(baggaget, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_baggageTActionPerformed

    private void rolesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rolesActionPerformed
        display.removeAll();
        roles role = new roles();
        display.add(role, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_rolesActionPerformed

    private void terminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terminalActionPerformed
        display.removeAll();
        Terminals termi = new Terminals();
        display.add(termi, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_terminalActionPerformed

    private void settiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settiActionPerformed
        display.removeAll();
        Settings settin = new Settings();
        display.add(settin, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_settiActionPerformed

    private void PassangerMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassangerMActionPerformed
        display.removeAll();
        PassengerManagement pm = new PassengerManagement();
        display.add(pm, BorderLayout.CENTER);
        SwingUtilities.updateComponentTreeUI(display);
    }//GEN-LAST:event_PassangerMActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        FlatIntelliJLaf.setup();
       
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenue().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PassangerM;
    private javax.swing.JButton act;
    private javax.swing.JButton aircraft;
    private javax.swing.JButton baggage;
    private javax.swing.JButton baggageT;
    private javax.swing.JButton dashBoardBtn;
    private javax.swing.JPanel display;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton roles;
    private javax.swing.JButton setti;
    private javax.swing.JButton terminal;
    // End of variables declaration//GEN-END:variables
}
