
package com.gatorsoft.aerodeskpro.gui;

import com.formdev.flatlaf.FlatIntelliJLaf;

public class SplashScreen extends javax.swing.JFrame {

   
    public SplashScreen() {
        initComponents();
        loadingAnimation();
    }
    
//    private void init() {
//        
//    }

    private void loadingAnimation() {
        Thread t = new Thread(new Runnable() {
            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    if (i > 10 && i < 30) {
                        jLabel1.setText("Starting modules " + i + " %");
                    } else if (i > 30 && i < 50) {
                        jLabel1.setText("Database Connection estabilished " + i + " %");
                    } else if (i > 50 && i < 80) {
                        jLabel1.setText("Almost Done " + i + " %");
                    } else if (i > 90) {
                        jLabel1.setText("Done.. " + i + " %");

                    }

                    System.out.println(i);
                    jProgressBar1.setValue(i);
                    try {
                        Thread.sleep(10);
                    } catch (InterruptedException ex) {
                        ex.addSuppressed(ex);
                    }
                }

                new SignIn().setVisible(true);                
                splashScreen.dispose();
            }
        });
        t.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 580, 10));

        jLabel2.setFont(new java.awt.Font("Consolas", 0, 14)); // NOI18N
        jLabel2.setText("Loading...");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 580, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/aerodeskpro/img/SplashScreenImg.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 420));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    private static SplashScreen splashScreen;

    public static void main(String args[]) {
      
        FlatIntelliJLaf.setup();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                splashScreen = new SplashScreen();
                splashScreen.setVisible(true);
            }
        });


//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            @Override
//            public void run() {
//                new SplashScreen().setVisible(true);
//            }
//        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
